<?php

namespace ContainerAdC4MzI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FyTYKh9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fyTYKh9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fyTYKh9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'product' => ['privates', '.errored..service_locator.fyTYKh9.App\\Entity\\Products', NULL, 'Cannot autowire service ".service_locator.fyTYKh9": it references class "App\\Entity\\Products" but no such service exists.'],
        ], [
            'product' => 'App\\Entity\\Products',
        ]);
    }
}
