<?php

namespace Container7SYvxBh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RKNvcDZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rKNvcDZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rKNvcDZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'product' => ['privates', '.errored..service_locator.rKNvcDZ.App\\Entity\\Products', NULL, 'Cannot autowire service ".service_locator.rKNvcDZ": it references class "App\\Entity\\Products" but no such service exists.'],
            'productsRepository' => ['privates', 'App\\Repository\\ProductsRepository', 'getProductsRepositoryService', true],
        ], [
            'product' => 'App\\Entity\\Products',
            'productsRepository' => 'App\\Repository\\ProductsRepository',
        ]);
    }
}
