<?php

namespace Container7SYvxBh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProducts2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.rKNvcDZ.App\Entity\Products' shared service.
     *
     * @return \App\Entity\Products
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.rKNvcDZ": it references class "App\\Entity\\Products" but no such service exists.');
    }
}
